
########################## 脱离eureka让zuul结合ribbon实现路由负载均衡  ##########################

zuul:
  routes:
    ribbon-route:
      path: /ribbon/**
      serviceId: ribbon-route
      strip-prefix: true

ribbon:
  eureka:
    enabled: false  #禁止Ribbon使用Eureka

ribbon-route:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule     #Ribbon LB Strategy
    NFLoadBalancerPingClassName: com.netflix.loadbalancer.PingUrl
    listOfServers: localhost:7070, localhost:7071    #client services for Ribbon LB